# 🧪 Notebook 05 — Evaluación semántica de vecinos recuperados con LLM

Esta notebook agrega una capa de evaluación semántica sobre los experimentos ANN realizados con Dialog2Flow.

La idea metodológica es separar tres planos:

1. **Eficiencia ANN:** las técnicas IVF, HNSW e IVFPQ permiten escalar la recuperación vectorial.
2. **Geometría de las representaciones dinámicas/acumulativas:** la acumulación modifica la estructura local de vecindad.
3. **Calidad semántico-funcional:** interesa observar si los vecinos recuperados son realmente útiles como situaciones conversacionales similares.

Esta notebook se enfoca en el tercer punto. Para eso:

- recupera vecinos `top-10` usando índices ANN;
- muestra ejemplos textuales de consultas y vecinos recuperados;
- usa un LLM de OpenAI como juez externo para asignar puntuaciones de similitud;
- calcula métricas agregadas como `Mean Semantic Score@10` y `SemanticHit@10`;
- exporta resultados en CSV y una tabla compacta para el paper.

> **Nota metodológica:** el juicio del LLM no reemplaza las métricas ANN. Se usa como evaluación complementaria y exploratoria de utilidad semántico-funcional sobre una muestra controlada de recuperaciones.

## 1️⃣ Instalación de dependencias

La notebook usa:

- `faiss-cpu` para construir los índices ANN;
- `openai` para consultar el LLM juez;
- `gdown` para descargar archivos desde Google Drive si no están montados;
- `pandas`, `numpy` y `tqdm` para manipulación y seguimiento.

In [ ]:
!pip install -q openai gdown faiss-cpu pandas numpy scikit-learn tqdm

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 32.7 MB/s eta 0:00:00

## 2️⃣ Configuración general

Por defecto la notebook está configurada para una corrida prudente. Para la corrida final del paper, se puede aumentar `N_QUERIES_LLM` y activar los tres modelos de embeddings.

La evaluación completa de 3 embeddings × 2 variantes × 3 índices puede consumir tiempo y crédito de API. La notebook permite hacer primero una prueba pequeña y luego escalar.

In [ ]:
import os
import json
import time
import shutil
from pathlib import Path
from getpass import getpass
from datetime import datetime
from zoneinfo import ZoneInfo

import gdown
import numpy as np
import pandas as pd
from tqdm.auto import tqdm
import faiss
from IPython.display import display, Markdown

# ============================================================
# Rutas principales
# ============================================================

# En Colab, conviene montar Drive y usar estas rutas.
DRIVE_DATA_DIR = Path("/content/drive/MyDrive/Doctorado/Cursos/ANN/TF/data/version2.0")
DRIVE_RESULTS_DIR = Path("/content/drive/MyDrive/Doctorado/Cursos/ANN/TF/resultados")

# Carpeta local de trabajo. Si los archivos existen en Drive, se copian o se leen desde allí.
LOCAL_DATA_DIR = Path("./data_version2")
LOCAL_RESULTS_DIR = Path("./resultados_semantic_llm")
LOCAL_DATA_DIR.mkdir(parents=True, exist_ok=True)
LOCAL_RESULTS_DIR.mkdir(parents=True, exist_ok=True)

# ============================================================
# Configuración experimental
# ============================================================

# Para prueba rápida, dejar solo Dialog2Flow. Para la tabla final, activar los tres.
EMBEDDINGS_A_EVALUAR = [
    "dialog2flow-joint-bert-base",
#    "all-MiniLM-L6-v2",
#    "all-mpnet-base-v2",
]

# Variantes de representación.
VARIANTES_A_EVALUAR = ["estatico", "dinamico"]

# Técnicas ANN para la prueba semántica de fuerza.
INDICES_A_EVALUAR = ["IVF", "HNSW", "IVFPQ"]

# Top-k semántico. El paper viene trabajando con Recall@10; mantenemos el mismo k.
K_EVAL = 10

# Cantidad de consultas para construir una muestra de evaluación semántica.
# Para smoke test: 3 a 5. Para paper: 30, 50 o 100 según presupuesto.
N_QUERIES_LLM = 100

# Split compatible con las notebooks previas.
N_QUERIES_SPLIT = 10000
RANDOM_STATE = 42

# Contexto textual que se le muestra al LLM juez.
# 2 significa: dos turnos previos + turno actual.
CONTEXT_WINDOW = 2

# Parámetros ANN representativos, consistentes con las tablas del paper.
N_LIST = 4096
N_PROBE = 64
HNSW_M = 32
HNSW_EF_CONSTRUCTION = 200
HNSW_EF_SEARCH = 256
PQ_M = 32
PQ_NBITS = 8
N_TRAIN_IVF = 100_000

# Seguridad/costo de API.
OPENAI_MODEL = "gpt-4.1-mini"  # Puede cambiarse por otro modelo disponible en la cuenta.
TEMPERATURE = 0
SLEEP_BETWEEN_CALLS = 0.2


print("Embeddings a evaluar:", EMBEDDINGS_A_EVALUAR)
print("Variantes:", VARIANTES_A_EVALUAR)
print("Índices ANN:", INDICES_A_EVALUAR)
print("N_QUERIES_LLM:", N_QUERIES_LLM)

Embeddings a evaluar: ['dialog2flow-joint-bert-base']
Variantes: ['estatico', 'dinamico']
Índices ANN: ['IVF', 'HNSW', 'IVFPQ']
N_QUERIES_LLM: 100

## 3️⃣ Montaje opcional de Google Drive

Si estás en Colab y los archivos ya quedaron guardados por las notebooks anteriores, conviene montar Drive. Si no, la notebook intenta descargar los archivos principales desde los IDs de Google Drive conocidos.

In [ ]:
try:
    from google.colab import drive
    drive.mount("/content/drive")
    IN_COLAB = True
except Exception:
    IN_COLAB = False
    print("No parece estar ejecutándose en Colab. Se usará el sistema de archivos local.")

DRIVE_RESULTS_DIR.mkdir(parents=True, exist_ok=True) if DRIVE_RESULTS_DIR.exists() or IN_COLAB else None
LOCAL_RESULTS_DIR.mkdir(parents=True, exist_ok=True)

Mounted at /content/drive

## 4️⃣ Archivos de entrada

La notebook necesita:

- `dialogs-2.0.pkl`: dataframe con los turnos conversacionales;
- `ids.npy`: identificadores de filas;
- embeddings estáticos: `embeddings_minilm.npy`, `embeddings_mpnet.npy`, `embeddings_dialog2flow.npy`;
- embeddings dinámicos/acumulativos, si ya fueron generados: `dynamic_embeddings_minilm.npy`, `dynamic_embeddings_mpnet.npy`, `accumulative_embeddings_dialog2flow.npy`.

Si los embeddings dinámicos no existen, la notebook puede generarlos usando la misma regla acumulativa normalizada de las notebooks previas.

In [ ]:
# IDs de Google Drive usados en las notebooks previas.
GOOGLE_DRIVE_IDS = {
    "dialogs-2.0.pkl": "1kRbmvg3NB96pWMUl866GZRrT6Zq9vxcb",
    "ids.npy": "1hWC7nLvSboFHyykjr7VFAEmcvz8re1cY",
    "embeddings_minilm.npy": "1imF_9lIGgGRJ7KQm-KhRPyinDUqPI_fW",
    "embeddings_mpnet.npy": "1ndtChhGE3U5bkJ59NvuXhbX5Bgr7uOGe",
    "embeddings_dialog2flow.npy": "1Pxf6oho0HYwv3B8VObZ_R6asShyK1WFW",
}

EMBEDDING_INFO = {
    "dialog2flow-joint-bert-base": {
        "label": "Dialog2Flow",
        "short": "dialog2flow",
        "static_file": "embeddings_dialog2flow.npy",
        "dynamic_file": "accumulative_embeddings_dialog2flow.npy",
    },
}


def ensure_file(filename: str) -> Path:
    """Devuelve una ruta local al archivo. Busca primero local, luego Drive, luego descarga por gdown si hay ID."""
    local_path = LOCAL_DATA_DIR / filename
    drive_path = DRIVE_DATA_DIR / filename

    if local_path.exists():
        return local_path

    if drive_path.exists():
        print(f"Copiando desde Drive: {drive_path} -> {local_path}")
        shutil.copy(drive_path, local_path)
        return local_path

    if filename in GOOGLE_DRIVE_IDS:
        file_id = GOOGLE_DRIVE_IDS[filename]
        url = f"https://drive.google.com/uc?id={file_id}"
        print(f"Descargando {filename} desde Google Drive...")
        gdown.download(url, str(local_path), quiet=False)
        return local_path

    raise FileNotFoundError(
        f"No se encontró {filename}. Busqué en {local_path} y {drive_path}. "
        "Si es un embedding dinámico, ejecutá antes la notebook 03 o activá su generación en esta notebook."
    )

ruta_df = ensure_file("dialogs-2.0.pkl")
ruta_ids = ensure_file("ids.npy")

df = pd.read_pickle(ruta_df)
ids = np.load(ruta_ids)

print("DataFrame:", df.shape)
print("IDs:", ids.shape)
display(df.head())

Copiando desde Drive: /content/drive/MyDrive/Doctorado/Cursos/ANN/TF/data/version2.0/dialogs-2.0.pkl -> data_version2/dialogs-2.0.pkl
Copiando desde Drive: /content/drive/MyDrive/Doctorado/Cursos/ANN/TF/data/version2.0/ids.npy -> data_version2/ids.npy
DataFrame: (1000023, 11)
IDs: (1000023,)

,dataset,split,dialogue_id,turn_id,speaker,utterance,domains,dialog_acts,main_acts,slots,intents
0,ABCD,test,ABCD_test_0,0,user,Hi. My name is Chloe Zhang. I am curious as ...,[storewide query],None,None,None,[timing]
1,ABCD,test,ABCD_test_1,0,user,Hello. I recently signed up for a subscription...,[subscription inquiry],None,None,None,[manage dispute bill]
2,ABCD,test,ABCD_test_1,1,user,"sure, it's Albert Sanders and my account id is...",[subscription inquiry],None,None,[account id],None
3,ABCD,test,ABCD_test_1,2,user,yes its 7149958247,[subscription inquiry],None,None,[order id],None
4,ABCD,test,ABCD_test_2,0,user,I'm thinking about buying an item but first i ...,[single item query],None,None,None,[shirt]

## 5️⃣ Funciones auxiliares para contexto textual

Para que el juicio del LLM no sea puramente local, se muestra el turno actual junto con algunos turnos previos del mismo diálogo. Esto ayuda a evaluar similitud como **situación conversacional**, no sólo como semejanza superficial entre frases.

In [ ]:
# Precomputamos grupos por diálogo para recuperar contexto rápido.
_df_ordered = df.reset_index().rename(columns={"index": "row_id"})
_dialogue_groups = {
    dialogue_id: g.sort_values("turn_id")["row_id"].tolist()
    for dialogue_id, g in _df_ordered.groupby("dialogue_id", sort=False)
}
_row_to_pos = {}
for dialogue_id, rows in _dialogue_groups.items():
    for pos, row_id in enumerate(rows):
        _row_to_pos[row_id] = pos


def get_context_rows(row_id: int, window: int = 2):
    """Devuelve los row_id de los turnos previos y actual dentro del mismo diálogo."""
    dialogue_id = df.loc[row_id, "dialogue_id"]
    rows = _dialogue_groups[dialogue_id]
    pos = _row_to_pos[row_id]
    start = max(0, pos - window)
    return rows[start:pos + 1]


def format_turn(row_id: int) -> str:
    r = df.loc[row_id]
    speaker = r.get("speaker", "?")
    utterance = str(r.get("utterance", ""))
    return f"[{int(r.get('turn_id', -1))}] {speaker}: {utterance}"


def format_situation(row_id: int, window: int = 2) -> str:
    rows = get_context_rows(row_id, window=window)
    lines = [format_turn(rid) for rid in rows]
    return "\n".join(lines)


def compact_metadata(row_id: int) -> dict:
    cols = ["dataset", "split", "dialogue_id", "turn_id", "speaker", "domains", "main_acts", "intents", "slots"]
    out = {}
    for c in cols:
        if c in df.columns:
            value = df.loc[row_id, c]
            out[c] = value
    return out

# Ejemplo rápido
example_row = int(df.index[10])
print(format_situation(example_row, window=CONTEXT_WINDOW))
compact_metadata(example_row)

[0] user: I'm looking at a pair of boots on your website and the size I want says unavailable.

{'dataset': 'ABCD',
 'split': 'test',
 'dialogue_id': 'ABCD_test_8',
 'turn_id': np.int64(0),
 'speaker': 'user',
 'domains': ['single item query'],
 'main_acts': None,
 'intents': ['boot'],
 'slots': None}

## 6️⃣ Split de consultas e indexación

Usamos el mismo esquema de separación de las notebooks anteriores: una muestra de consultas se excluye de la base indexada, evitando que una consulta recupere su propio vector como vecino.

Para la evaluación con LLM se toma una submuestra pequeña de esas consultas.

In [ ]:
def preparar_split(n_total: int, n_queries: int, random_state: int):
    rng = np.random.default_rng(random_state)
    query_idx = rng.choice(n_total, size=n_queries, replace=False)
    mask = np.ones(n_total, dtype=bool)
    mask[query_idx] = False
    index_idx = np.where(mask)[0]
    return index_idx.astype("int64"), query_idx.astype("int64")

index_idx, query_idx_full = preparar_split(len(df), N_QUERIES_SPLIT, RANDOM_STATE)

rng = np.random.default_rng(RANDOM_STATE + 100)
query_sample = rng.choice(
    query_idx_full,
    size=min(N_QUERIES_LLM, len(query_idx_full)),
    replace=False
).astype("int64")

print("Vectores indexados:", len(index_idx))
print("Consultas split completo:", len(query_idx_full))
print("Consultas para LLM:", len(query_sample))
print("Primeras consultas muestreadas:", query_sample[:10])

Vectores indexados: 990023
Consultas split completo: 10000
Consultas para LLM: 100
Primeras consultas muestreadas: [258133 185989 734763 306913 846179 332360 169096 447851 940288 337047]

## 7️⃣ Generación opcional de representaciones dinámicas/acumulativas

Si las representaciones dinámicas ya fueron generadas por las notebooks 03, esta sección simplemente las carga. Si no existen, se pueden generar acá.

La regla es la misma del paper:

\[
h_t = \mathrm{LayerNorm}(h_{t-1} + e_t)
\]

Esta representación debe interpretarse como una variante acumulativa liviana del historial, no como un modelo supervisado de estado de diálogo.

In [ ]:
GENERAR_DINAMICO_SI_FALTA = True


def layer_norm_np(x: np.ndarray, eps: float = 1e-5) -> np.ndarray:
    mean = x.mean()
    var = x.var()
    return (x - mean) / np.sqrt(var + eps)


def generar_dynamic_embeddings(static_path: Path, dynamic_path: Path):
    """Genera embeddings dinámicos/acumulativos en formato memmap .npy."""
    static = np.load(static_path, mmap_mode="r")
    n, d = static.shape

    print(f"Generando representación dinámica: {dynamic_path.name}")
    print("Shape:", static.shape)

    dyn = np.lib.format.open_memmap(
        dynamic_path,
        mode="w+",
        dtype="float32",
        shape=(n, d),
    )

    t0 = time.time()
    for i, (dialogue_id, grupo) in enumerate(tqdm(df.groupby("dialogue_id", sort=False))):
        grupo = grupo.sort_values("turn_id")
        h = np.zeros(d, dtype="float32")

        for row_id in grupo.index.to_numpy():
            e = np.asarray(static[row_id], dtype="float32")
            h = layer_norm_np(h + e).astype("float32")
            dyn[row_id] = h

        if (i + 1) % 10000 == 0:
            dyn.flush()

    dyn.flush()
    print("Finalizado en", round(time.time() - t0, 2), "segundos")
    return dynamic_path


def get_embedding_path(embedding_name: str, variante: str) -> Path:
    info = EMBEDDING_INFO[embedding_name]
    if variante == "estatico":
        return ensure_file(info["static_file"])
    elif variante == "dinamico":
        filename = info["dynamic_file"]
        local_path = LOCAL_DATA_DIR / filename
        drive_path = DRIVE_DATA_DIR / filename
        if local_path.exists():
            return local_path
        if drive_path.exists():
            print(f"Copiando dinámica desde Drive: {drive_path} -> {local_path}")
            shutil.copy(drive_path, local_path)
            return local_path
        if GENERAR_DINAMICO_SI_FALTA:
            static_path = get_embedding_path(embedding_name, "estatico")
            return generar_dynamic_embeddings(static_path, local_path)
        raise FileNotFoundError(f"Falta {filename} y GENERAR_DINAMICO_SI_FALTA=False")
    else:
        raise ValueError("variante debe ser 'estatico' o 'dinamico'")

## 8️⃣ Construcción de índices ANN y recuperación top-10

Esta sección construye una configuración representativa de cada técnica ANN y recupera `top-10` vecinos para la muestra de consultas.

Configuraciones usadas:

- IVF: `nlist=4096`, `nprobe=64`;
- HNSW: `M=32`, `efConstruction=200`, `efSearch=256`;
- IVFPQ: `nlist=4096`, `m=32`, `nbits=8`, `nprobe=64`.

La tabla semántica se construye sobre estas recuperaciones.

In [ ]:
# ============================================================
# Diagnóstico y limpieza de archivos .npy corruptos/truncados
# ============================================================

import os
from pathlib import Path
import numpy as np

archivos_npy = [
    "ids.npy",
    "embeddings_minilm.npy",
    "embeddings_mpnet.npy",
    "embeddings_dialog2flow.npy",
    "dynamic_embeddings_minilm.npy",
    "dynamic_embeddings_mpnet.npy",
    "accumulative_embeddings_dialog2flow.npy",
]

def probar_npy(path):
    try:
        arr = np.load(path, mmap_mode="r")
        shape = arr.shape
        dtype = arr.dtype
        size_mb = path.stat().st_size / (1024**2)
        print(f"OK   {path.name:40s} | {size_mb:9.2f} MB | shape={shape} | dtype={dtype}")
        return True
    except Exception as e:
        size_mb = path.stat().st_size / (1024**2) if path.exists() else 0
        print(f"BAD  {path.name:40s} | {size_mb:9.2f} MB | ERROR: {e}")
        return False

corruptos = []

for filename in archivos_npy:
    local_path = LOCAL_DATA_DIR / filename
    drive_path = DRIVE_DATA_DIR / filename

    if local_path.exists():
        ok = probar_npy(local_path)
        if not ok:
            corruptos.append(local_path)

    elif drive_path.exists():
        ok = probar_npy(drive_path)
        if not ok:
            corruptos.append(drive_path)

    else:
        print(f"MISS {filename:40s} | no encontrado")

print("\nArchivos corruptos detectados:")
for p in corruptos:
    print("-", p)

OK   ids.npy                                  |      7.63 MB | shape=(1000023,) | dtype=int64
OK   embeddings_minilm.npy                    |   1464.88 MB | shape=(1000023, 384) | dtype=float32
OK   embeddings_mpnet.npy                     |   2929.76 MB | shape=(1000023, 768) | dtype=float32
OK   embeddings_dialog2flow.npy               |   2929.76 MB | shape=(1000023, 768) | dtype=float32
OK   dynamic_embeddings_minilm.npy            |   1464.88 MB | shape=(1000023, 384) | dtype=float32
OK   dynamic_embeddings_mpnet.npy             |   2929.76 MB | shape=(1000023, 768) | dtype=float32
OK   accumulative_embeddings_dialog2flow.npy  |   2929.76 MB | shape=(1000023, 768) | dtype=float32

Archivos corruptos detectados:

In [ ]:
# ============================================================
# Eliminar copias locales corruptas para forzar redescarga/regeneración
# ============================================================

for p in corruptos:
    # Sólo borro archivos dentro de LOCAL_DATA_DIR.
    # Si el corrupto está en Drive, conviene revisarlo manualmente.
    if str(p).startswith(str(LOCAL_DATA_DIR)):
        print("Eliminando local corrupto:", p)
        p.unlink()
    else:
        print("OJO: corrupto en Drive, no lo borro automáticamente:", p)

In [ ]:
def normalize_copy(x: np.ndarray) -> np.ndarray:
    x = np.asarray(x, dtype="float32").copy()
    faiss.normalize_L2(x)
    return x


def build_ann_index(index_type: str, index_vectors: np.ndarray, random_state: int = 42):
    n, d = index_vectors.shape

    if index_type == "IVF":
        quantizer = faiss.IndexFlatL2(d)
        index = faiss.IndexIVFFlat(quantizer, d, N_LIST, faiss.METRIC_L2)
        rng = np.random.default_rng(random_state)
        train_size = min(N_TRAIN_IVF, n)
        train_idx = rng.choice(n, size=train_size, replace=False)
        index.train(index_vectors[train_idx])
        index.add(index_vectors)
        index.nprobe = N_PROBE
        return index

    if index_type == "HNSW":
        index = faiss.IndexHNSWFlat(d, HNSW_M)
        index.hnsw.efConstruction = HNSW_EF_CONSTRUCTION
        index.add(index_vectors)
        index.hnsw.efSearch = HNSW_EF_SEARCH
        return index

    if index_type == "IVFPQ":
        if d % PQ_M != 0:
            raise ValueError(f"La dimensión {d} no es divisible por PQ_M={PQ_M}")
        quantizer = faiss.IndexFlatL2(d)
        index = faiss.IndexIVFPQ(quantizer, d, N_LIST, PQ_M, PQ_NBITS)
        rng = np.random.default_rng(random_state)
        train_size = min(N_TRAIN_IVF, n)
        train_idx = rng.choice(n, size=train_size, replace=False)
        index.train(index_vectors[train_idx])
        index.add(index_vectors)
        index.nprobe = N_PROBE
        return index

    raise ValueError(f"Índice no reconocido: {index_type}")


def retrieve_topk_for_config(embedding_name: str, variante: str, index_type: str, k: int = 10):
    path = get_embedding_path(embedding_name, variante)
    matriz = np.load(path, mmap_mode="r")

    print("=" * 80)
    print("Embedding:", embedding_name)
    print("Variante:", variante)
    print("Índice:", index_type)
    print("Archivo:", path)
    print("Shape:", matriz.shape)

    # Copias normalizadas para FAISS. La query sample es pequeña; la base indexada es grande.
    index_vectors = normalize_copy(matriz[index_idx])
    query_vectors = normalize_copy(matriz[query_sample])

    t0 = time.time()
    index = build_ann_index(index_type, index_vectors, random_state=RANDOM_STATE)
    build_time = time.time() - t0

    t1 = time.time()
    distances, local_neighbors = index.search(query_vectors, k)
    search_time = time.time() - t1

    # Convertimos posiciones locales del índice FAISS a row_id originales del dataframe.
    neighbor_rows = index_idx[local_neighbors]

    records = []
    label = EMBEDDING_INFO[embedding_name]["label"]
    for q_pos, q_row in enumerate(query_sample):
        for rank in range(k):
            n_row = int(neighbor_rows[q_pos, rank])
            records.append({
                "embedding_name": embedding_name,
                "embedding_base": label,
                "variant": variante,
                "index_type": index_type,
                "query_order": int(q_pos),
                "query_row": int(q_row),
                "neighbor_rank": int(rank + 1),
                "neighbor_row": n_row,
                "distance": float(distances[q_pos, rank]),
                "query_utterance": str(df.loc[int(q_row), "utterance"]),
                "neighbor_utterance": str(df.loc[n_row, "utterance"]),
                "query_context": format_situation(int(q_row), window=CONTEXT_WINDOW),
                "neighbor_context": format_situation(n_row, window=CONTEXT_WINDOW),
                "build_time_s": build_time,
                "search_time_s": search_time,
            })

    # Liberación explícita de memoria.
    del index_vectors, query_vectors, index, distances, local_neighbors, neighbor_rows, matriz
    return pd.DataFrame(records)


def run_all_retrievals():
    all_parts = []
    for embedding_name in EMBEDDINGS_A_EVALUAR:
        for variante in VARIANTES_A_EVALUAR:
            for index_type in INDICES_A_EVALUAR:
                df_part = retrieve_topk_for_config(embedding_name, variante, index_type, k=K_EVAL)
                all_parts.append(df_part)
    return pd.concat(all_parts, ignore_index=True)

# Ejecutar recuperación.
df_retrieval = run_all_retrievals()
print("Recuperaciones generadas:", df_retrieval.shape)
display(df_retrieval.head())

Copiando desde Drive: /content/drive/MyDrive/Doctorado/Cursos/ANN/TF/data/version2.0/embeddings_dialog2flow.npy -> data_version2/embeddings_dialog2flow.npy
================================================================================
Embedding: dialog2flow-joint-bert-base
Variante: estatico
Índice: IVF
Archivo: data_version2/embeddings_dialog2flow.npy
Shape: (1000023, 768)
================================================================================
Embedding: dialog2flow-joint-bert-base
Variante: estatico
Índice: HNSW
Archivo: data_version2/embeddings_dialog2flow.npy
Shape: (1000023, 768)
================================================================================
Embedding: dialog2flow-joint-bert-base
Variante: estatico
Índice: IVFPQ
Archivo: data_version2/embeddings_dialog2flow.npy
Shape: (1000023, 768)
Copiando dinámica desde Drive: /content/drive/MyDrive/Doctorado/Cursos/ANN/TF/data/version2.0/accumulative_embeddings_dialog2flow.npy -> data_version2/accumulative_embeddings_dialog2flow.npy
================================================================================
Embedding: dialog2flow-joint-bert-base
Variante: dinamico
Índice: IVF
Archivo: data_version2/accumulative_embeddings_dialog2flow.npy
Shape: (1000023, 768)
================================================================================
Embedding: dialog2flow-joint-bert-base
Variante: dinamico
Índice: HNSW
Archivo: data_version2/accumulative_embeddings_dialog2flow.npy
Shape: (1000023, 768)
================================================================================
Embedding: dialog2flow-joint-bert-base
Variante: dinamico
Índice: IVFPQ
Archivo: data_version2/accumulative_embeddings_dialog2flow.npy
Shape: (1000023, 768)
Recuperaciones generadas: (6000, 15)

,embedding_name,embedding_base,variant,index_type,query_order,query_row,neighbor_rank,neighbor_row,distance,query_utterance,neighbor_utterance,query_context,neighbor_context,build_time_s,search_time_s
0,dialog2flow-joint-bert-base,Dialog2Flow,estatico,IVF,0,258133,1,572964,5.911047e-13,"oh , i completely forgot to mention that i wil...","Oh, I completely forgot to mention that I will...",[6] user: i 'd also like to find a 4 star hote...,[8] user: I'd also like to find a 4 star hotel...,264.246174,0.52403
1,dialog2flow-joint-bert-base,Dialog2Flow,estatico,IVF,0,258133,2,92687,5.996744e-13,"oh , i completely forgot to mention that i wil...","oh, i completely forgot to mention that i will...",[6] user: i 'd also like to find a 4 star hote...,[8] user: i'd also like to find a 4 star hotel...,264.246174,0.52403
2,dialog2flow-joint-bert-base,Dialog2Flow,estatico,IVF,0,258133,3,683102,1.183576e-12,"oh , i completely forgot to mention that i wil...","Oh, I completely forgot to mention that I will...",[6] user: i 'd also like to find a 4 star hote...,[3] user: The booking will be for only one per...,264.246174,0.52403
3,dialog2flow-joint-bert-base,Dialog2Flow,estatico,IVF,0,258133,4,116471,3.937679e-01,"oh , i completely forgot to mention that i wil...",oh i'm sorry i forgot to mention i must have a...,[6] user: i 'd also like to find a 4 star hote...,"[6] user: friday, for 1 person and will stay f...",264.246174,0.52403
4,dialog2flow-joint-bert-base,Dialog2Flow,estatico,IVF,0,258133,5,323472,3.937679e-01,"oh , i completely forgot to mention that i wil...",oh i 'm sorry i forgot to mention i must have ...,[6] user: i 'd also like to find a 4 star hote...,"[5] user: friday , for 1 person and will stay ...",264.246174,0.52403

## 9️⃣ Exploración textual de vecinos recuperados

Antes de usar el LLM como juez, conviene mirar ejemplos. Esta sección permite inspeccionar:

- la situación conversacional de consulta;
- sus vecinos top-10;
- el contexto de cada vecino;
- metadatos disponibles como dominio, actos, intents o slots.

Esto sirve para tener una percepción cualitativa de qué está recuperando cada configuración.

In [ ]:
def mostrar_vecinos(
    df_retrieval: pd.DataFrame,
    embedding_base: str = None,
    variante: str = None,
    index_type: str = None,
    query_order: int = 0,
    top_n: int = 10,
    mostrar_contexto_vecino: bool = True,
):
    sub = df_retrieval.copy()
    if embedding_base is not None:
        sub = sub[sub["embedding_base"] == embedding_base]
    if variante is not None:
        sub = sub[sub["variant"] == variante]
    if index_type is not None:
        sub = sub[sub["index_type"] == index_type]
    sub = sub[sub["query_order"] == query_order].sort_values("neighbor_rank").head(top_n)

    if sub.empty:
        print("No hay registros para ese filtro.")
        return

    first = sub.iloc[0]
    display(Markdown(f"### Consulta `{query_order}` — {first['embedding_base']} / {first['variant']} / {first['index_type']}"))
    display(Markdown("**Situación de consulta:**"))
    print(first["query_context"])
    display(Markdown("**Metadatos consulta:**"))
    display(pd.DataFrame([compact_metadata(int(first["query_row"]))]))

    rows = []
    for _, r in sub.iterrows():
        item = {
            "rank": int(r["neighbor_rank"]),
            "distance": round(float(r["distance"]), 4),
            "neighbor_row": int(r["neighbor_row"]),
            "neighbor_utterance": r["neighbor_utterance"],
        }
        if mostrar_contexto_vecino:
            item["neighbor_context"] = r["neighbor_context"]
        rows.append(item)
    display(pd.DataFrame(rows))


def comparar_estatico_dinamico(
    df_retrieval: pd.DataFrame,
    embedding_base: str = "Dialog2Flow",
    index_type: str = "HNSW",
    query_order: int = 0,
    top_n: int = 10,
):
    for variante in ["estatico", "dinamico"]:
        mostrar_vecinos(
            df_retrieval,
            embedding_base=embedding_base,
            variante=variante,
            index_type=index_type,
            query_order=query_order,
            top_n=top_n,
            mostrar_contexto_vecino=False,
        )

# Ejemplo inicial. Cambiar query_order, embedding_base, variante e index_type para explorar.
mostrar_vecinos(
    df_retrieval,
    embedding_base="Dialog2Flow",
    variante="dinamico",
    index_type="HNSW",
    query_order=0,
    top_n=10,
)

### Consulta `0` — Dialog2Flow / dinamico / HNSW

**Situación de consulta:**

[6] user: i 'd also like to find a 4 star hotel with free wifi , please .
[7] system: there are 3 hotels which are 4 stars , two in the west and one in the centre . is there an area which you prefer ?
[8] user: oh , i completely forgot to mention that i will also need a hotel that has free parking . any of the 7 you said have this option ?

**Metadatos consulta:**

,dataset,split,dialogue_id,turn_id,speaker,domains,main_acts,intents,slots
0,HDSA-Dialog,test,HDSA-Dialog_test_303,8,user,[hotel],[inform],None,[parking]

,rank,distance,neighbor_row,neighbor_utterance,neighbor_context
0,1,0.0312,92687,"oh, i completely forgot to mention that i will...",[8] user: i'd also like to find a 4 star hotel...
1,2,0.0312,572964,"Oh, I completely forgot to mention that I will...",[8] user: I'd also like to find a 4 star hotel...
2,3,0.0826,258132,"there are 3 hotels which are 4 stars , two in ...","[5] system: yes . the booking was successful ,..."
3,4,0.0845,258134,"huntingdon marriott hotel , the cambridge belf...",[7] system: there are 3 hotels which are 4 sta...
4,5,0.1067,92688,"huntingdon marriott hotel, the cambridge belfr...",[9] system: there are 3 hotels which are 4 sta...
5,6,0.1067,572965,"huntingdon marriott hotel, the cambridge belfr...",[9] system: There are 3 hotels which are 4 sta...
6,7,0.1087,92686,"there are 3 hotels which are 4 stars, two in t...","[7] system: yes. the booking was successful, t..."
7,8,0.1087,572963,"There are 3 hotels which are 4 stars, two in t...","[7] system: Yes. The booking was successful, ..."
8,9,0.1692,258131,i 'd also like to find a 4 star hotel with fre...,[4] system: would you like me to book 2 ticket...
9,10,0.1845,324668,it should include free parking . the hotel sho...,[6] system: two seats are booked for tr6742 . ...

## 🔟 Configuración de OpenAI

La API key se carga de forma segura. No se escribe la clave en la notebook.

La evaluación se hace con salida JSON estructurada para reducir problemas de parsing.

In [ ]:
from openai import OpenAI

os.environ["OPENAI_API_KEY"] = "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"

client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])
print("Cliente OpenAI configurado.")

Cliente OpenAI configurado.

## 1️⃣1️⃣ Prompt juez y esquema de salida

El LLM recibe una situación de consulta y diez vecinos recuperados. Para cada vecino devuelve cuatro puntuaciones enteras de 1 a 5:

- `semantic_similarity`: similitud temática/semántica del contenido;
- `functional_similarity`: similitud de función dentro del diálogo;
- `memory_usefulness`: utilidad del vecino como antecedente recuperado;
- `overall_similarity`: evaluación global para `MSS@10`.

Escala:

1. No relacionado.
2. Relación débil o superficial.
3. Similitud parcial.
4. Similitud clara y útil.
5. Situaciones altamente equivalentes.

In [ ]:
EVALUATION_SCHEMA = {
    "name": "dialog_retrieval_evaluation",
    "schema": {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "evaluations": {
                "type": "array",
                "minItems": K_EVAL,
                "maxItems": K_EVAL,
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "rank": {"type": "integer", "minimum": 1, "maximum": K_EVAL},
                        "semantic_similarity": {"type": "integer", "minimum": 1, "maximum": 5},
                        "functional_similarity": {"type": "integer", "minimum": 1, "maximum": 5},
                        "memory_usefulness": {"type": "integer", "minimum": 1, "maximum": 5},
                        "overall_similarity": {"type": "integer", "minimum": 1, "maximum": 5},
                        "brief_reason": {"type": "string"},
                    },
                    "required": [
                        "rank",
                        "semantic_similarity",
                        "functional_similarity",
                        "memory_usefulness",
                        "overall_similarity",
                        "brief_reason",
                    ],
                },
            }
        },
        "required": ["evaluations"],
    },
    "strict": True,
}

SYSTEM_PROMPT = """
You are an expert evaluator of task-oriented dialogue retrieval.
Your task is to judge whether retrieved dialogue situations are semantically and functionally similar to a query dialogue situation.
Focus on task-oriented dialogue behavior, not only lexical overlap.
Use the 1-5 scale consistently.
Return only valid JSON following the schema.
""".strip()


def build_judge_prompt(group: pd.DataFrame) -> str:
    group = group.sort_values("neighbor_rank")
    first = group.iloc[0]

    lines = []
    lines.append("Evaluate whether each retrieved neighbor is similar to the query situation.")
    lines.append("")
    lines.append("Scoring scale:")
    lines.append("1 = unrelated")
    lines.append("2 = weak or superficial relation")
    lines.append("3 = partial similarity")
    lines.append("4 = clear semantic/functional similarity")
    lines.append("5 = highly equivalent dialogue situations")
    lines.append("")
    lines.append("QUERY SITUATION:")
    lines.append(first["query_context"])
    lines.append("")
    lines.append("RETRIEVED NEIGHBORS:")

    for _, r in group.iterrows():
        lines.append("")
        lines.append(f"Neighbor rank {int(r['neighbor_rank'])}:")
        lines.append(r["neighbor_context"])

    lines.append("")
    lines.append("Return one evaluation object for each neighbor rank from 1 to 10.")
    return "\n".join(lines)


def evaluate_group_with_llm(group: pd.DataFrame, model: str = OPENAI_MODEL) -> dict:
    user_prompt = build_judge_prompt(group)

    response = client.chat.completions.create(
        model=model,
        temperature=TEMPERATURE,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        response_format={
            "type": "json_schema",
            "json_schema": EVALUATION_SCHEMA,
        },
    )

    content = response.choices[0].message.content
    return json.loads(content)

# Prueba opcional de prompt sin llamar a la API.
_test_group = df_retrieval.groupby(["embedding_base", "variant", "index_type", "query_order"]).get_group(
    (df_retrieval.iloc[0]["embedding_base"], df_retrieval.iloc[0]["variant"], df_retrieval.iloc[0]["index_type"], df_retrieval.iloc[0]["query_order"])
)
print(build_judge_prompt(_test_group)[:2500])

Evaluate whether each retrieved neighbor is similar to the query situation.

Scoring scale:
1 = unrelated
2 = weak or superficial relation
3 = partial similarity
4 = clear semantic/functional similarity
5 = highly equivalent dialogue situations

QUERY SITUATION:
[6] user: i 'd also like to find a 4 star hotel with free wifi , please .
[7] system: there are 3 hotels which are 4 stars , two in the west and one in the centre . is there an area which you prefer ?
[8] user: oh , i completely forgot to mention that i will also need a hotel that has free parking . any of the 7 you said have this option ?

RETRIEVED NEIGHBORS:

Neighbor rank 1:
[8] user: I'd also like to find a 4 star hotel with free wifi, please.
[9] system: There are 3 hotels which are 4 stars, two in the west and one in the centre. Is there an area which you prefer?
[10] user: Oh, I completely forgot to mention that I will also need a hotel that has free parking. Any of the 7 you said have this option?

Neighbor rank 2:
[8] user: i'd also like to find a 4 star hotel with free wifi, please.
[9] system: there are 3 hotels which are 4 stars, two in the west and one in the centre. is there an area which you prefer?
[10] user: oh, i completely forgot to mention that i will also need a hotel that has free parking. any of the 7 you said have this option?

Neighbor rank 3:
[3] user: The booking will be for only one person, and can I please have a reference number as well?
[4] user: I'd also like to find a 4 star hotel with free wifi, please.
[5] user: Oh, I completely forgot to mention that I will also need a hotel that has free parking. Any of the 7 you said have this option?

Neighbor rank 4:
[6] user: friday, for 1 person and will stay for 2 days. can you book it for me ?
[7] system: el shaddai has been booked for you for friday.
[8] user: oh i'm sorry i forgot to mention i must have a hotel that includes free parking.

Neighbor rank 5:
[5] user: friday , for 1 person and will stay for 2 days . can you book it for me ?
[6] system: el shaddai has been booked for you for friday .
[7] user: oh i 'm sorry i forgot to mention i must have a hotel that includes free parking .

Neighbor rank 6:
[2] user: I would like it in the centre.
[3] user: Friday, for 1 person and will stay for 2 days. Can you book it for me ?
[4] user: Oh I'm sorry I forgot to mention I must have a hotel that includes free parking.

Neighbor rank 7:
[1] system: i found five expensive hotels with free parking. what part of town are you

## 1️⃣2️⃣ Evaluación con LLM y cache

Para evitar repetir llamadas pagas, los resultados se guardan en `JSONL`. Si la notebook se interrumpe, puede continuar desde el cache.

In [ ]:
timestamp = datetime.now(ZoneInfo("America/Argentina/Buenos_Aires")).strftime("%Y%m%d_%H%M%S_ARG")
CACHE_PATH = LOCAL_RESULTS_DIR / f"llm_semantic_scores_cache_{timestamp}.jsonl"

# Si querés continuar una corrida previa, reemplazá CACHE_PATH por el archivo existente.
print("Cache actual:", CACHE_PATH)


def config_key_from_group(group: pd.DataFrame) -> str:
    first = group.iloc[0]
    return "|".join([
        str(first["embedding_base"]),
        str(first["variant"]),
        str(first["index_type"]),
        str(first["query_order"]),
        str(first["query_row"]),
        OPENAI_MODEL,
    ])


def load_existing_cache(path: Path) -> set:
    done = set()
    if not path.exists():
        return done
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rec = json.loads(line)
                done.add(rec["config_key"])
    return done


def append_jsonl(path: Path, record: dict):
    with open(path, "a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def run_llm_evaluation(df_retrieval: pd.DataFrame, cache_path: Path):
    group_cols = ["embedding_base", "variant", "index_type", "query_order"]
    groups = list(df_retrieval.groupby(group_cols, sort=False))
    done = load_existing_cache(cache_path)

    print("Grupos a evaluar:", len(groups))
    print("Ya evaluados en cache:", len(done))

    for key, group in tqdm(groups):
        group = group.sort_values("neighbor_rank")
        config_key = config_key_from_group(group)
        if config_key in done:
            continue

        try:
            result = evaluate_group_with_llm(group, model=OPENAI_MODEL)
            record = {
                "config_key": config_key,
                "embedding_base": key[0],
                "variant": key[1],
                "index_type": key[2],
                "query_order": int(key[3]),
                "query_row": int(group.iloc[0]["query_row"]),
                "model": OPENAI_MODEL,
                "evaluations": result["evaluations"],
            }
            append_jsonl(cache_path, record)
            done.add(config_key)
            time.sleep(SLEEP_BETWEEN_CALLS)
        except Exception as e:
            print("Error en", key, "->", repr(e))
            # No se corta toda la corrida; se puede inspeccionar luego.
            time.sleep(2)

    print("Evaluación terminada.")

# Ejecutar llamadas al LLM.
run_llm_evaluation(df_retrieval, CACHE_PATH)

Cache actual: resultados_semantic_llm/llm_semantic_scores_cache_20260529_185158_ARG.jsonl
Grupos a evaluar: 600
Ya evaluados en cache: 0

  0%|          | 0/600 [00:00<?, ?it/s]

Evaluación terminada.

## 1️⃣3️⃣ Conversión del cache a DataFrame

Cada llamada evalúa los diez vecinos de una consulta para una configuración. Ahora convertimos esas evaluaciones a una tabla a nivel de par consulta-vecino.

In [ ]:
def cache_to_dataframe(cache_path: Path, df_retrieval: pd.DataFrame) -> pd.DataFrame:
    records = []
    if not cache_path.exists():
        raise FileNotFoundError(cache_path)

    with open(cache_path, "r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            rec = json.loads(line)
            for ev in rec["evaluations"]:
                out = {
                    "embedding_base": rec["embedding_base"],
                    "variant": rec["variant"],
                    "index_type": rec["index_type"],
                    "query_order": rec["query_order"],
                    "query_row": rec["query_row"],
                    "model": rec["model"],
                    **ev,
                }
                records.append(out)

    scores = pd.DataFrame(records)
    scores = scores.rename(columns={"rank": "neighbor_rank"})

    merge_cols = ["embedding_base", "variant", "index_type", "query_order", "query_row", "neighbor_rank"]
    enriched = scores.merge(
        df_retrieval,
        on=merge_cols,
        how="left",
        validate="one_to_one",
    )
    return enriched


df_scores = cache_to_dataframe(CACHE_PATH, df_retrieval)
print(df_scores.shape)
display(df_scores.head())

(6000, 21)

,embedding_base,variant,index_type,query_order,query_row,model,neighbor_rank,semantic_similarity,functional_similarity,memory_usefulness,...,brief_reason,embedding_name,neighbor_row,distance,query_utterance,neighbor_utterance,query_context,neighbor_context,build_time_s,search_time_s
0,Dialog2Flow,estatico,IVF,0,258133,gpt-4.1-mini,1,5,5,5,...,Exact match of dialogue turns and user request...,dialog2flow-joint-bert-base,572964,5.911047e-13,"oh , i completely forgot to mention that i wil...","Oh, I completely forgot to mention that I will...",[6] user: i 'd also like to find a 4 star hote...,[8] user: I'd also like to find a 4 star hotel...,264.246174,0.52403
1,Dialog2Flow,estatico,IVF,0,258133,gpt-4.1-mini,2,5,5,5,...,Exact match of dialogue turns and user request...,dialog2flow-joint-bert-base,92687,5.996744e-13,"oh , i completely forgot to mention that i wil...","oh, i completely forgot to mention that i will...",[6] user: i 'd also like to find a 4 star hote...,[8] user: i'd also like to find a 4 star hotel...,264.246174,0.52403
2,Dialog2Flow,estatico,IVF,0,258133,gpt-4.1-mini,3,3,3,3,...,Partial overlap in user requests about 4 star ...,dialog2flow-joint-bert-base,683102,1.183576e-12,"oh , i completely forgot to mention that i wil...","Oh, I completely forgot to mention that I will...",[6] user: i 'd also like to find a 4 star hote...,[3] user: The booking will be for only one per...,264.246174,0.52403
3,Dialog2Flow,estatico,IVF,0,258133,gpt-4.1-mini,4,3,3,3,...,User requests free parking and booking details...,dialog2flow-joint-bert-base,116471,3.937679e-01,"oh , i completely forgot to mention that i wil...",oh i'm sorry i forgot to mention i must have a...,[6] user: i 'd also like to find a 4 star hote...,"[6] user: friday, for 1 person and will stay f...",264.246174,0.52403
4,Dialog2Flow,estatico,IVF,0,258133,gpt-4.1-mini,5,3,3,3,...,"Similar to rank 4, booking and free parking me...",dialog2flow-joint-bert-base,323472,3.937679e-01,"oh , i completely forgot to mention that i wil...",oh i 'm sorry i forgot to mention i must have ...,[6] user: i 'd also like to find a 4 star hote...,"[5] user: friday , for 1 person and will stay ...",264.246174,0.52403

## 1️⃣4️⃣ Métricas agregadas: MSS@10

Definimos primero el puntaje semántico por consulta:

\[
SS@10(q) = \frac{1}{10} \sum_{i=1}^{10} score(q, v_i)
\]

Luego, para cada configuración de embedding, variante e índice ANN, calculamos:

\[
MSS@10 = \frac{1}{|Q|} \sum_{q \in Q} SS@10(q)
\]

La unidad estadística para resumir la variabilidad es la **consulta**, no cada par query-vecino. Por eso también reportamos el **desvío estándar entre consultas** (`SD`) y el **error estándar** (`SE`) de `SS@10(q)`.

In [ ]:
# Métricas por query/configuración.
# Cada fila de query_metrics representa una query evaluada para una configuración.
# mss_at10 es SS@10(q): promedio de los 10 vecinos recuperados para esa query.
query_metrics = (
    df_scores
    .groupby(["embedding_base", "variant", "index_type", "query_order"], as_index=False)
    .agg(
        semantic_score_at10=("semantic_similarity", "mean"),
        functional_score_at10=("functional_similarity", "mean"),
        memory_score_at10=("memory_usefulness", "mean"),
        mss_at10=("overall_similarity", "mean"),
    )
)

# Métricas agregadas por configuración.
# Reportamos media, desvío estándar y error estándar del MSS@10 entre queries.
summary_metrics = (
    query_metrics
    .groupby(["embedding_base", "variant", "index_type"], as_index=False)
    .agg(
        n_queries=("query_order", "nunique"),
        mean_semantic_score_at10=("semantic_score_at10", "mean"),
        sd_semantic_score_at10=("semantic_score_at10", "std"),
        mean_functional_score_at10=("functional_score_at10", "mean"),
        sd_functional_score_at10=("functional_score_at10", "std"),
        mean_memory_score_at10=("memory_score_at10", "mean"),
        sd_memory_score_at10=("memory_score_at10", "std"),
        mean_semantic_score_global_at10=("mss_at10", "mean"),
        sd_semantic_score_global_at10=("mss_at10", "std"),
    )
)

summary_metrics["se_semantic_score_global_at10"] = (
    summary_metrics["sd_semantic_score_global_at10"] / np.sqrt(summary_metrics["n_queries"])
)

# IC 95% aproximado, útil para inspección; no es obligatorio reportarlo en el paper.
summary_metrics["ci95_semantic_score_global_at10"] = 1.96 * summary_metrics["se_semantic_score_global_at10"]

for col in summary_metrics.select_dtypes(include=["float"]).columns:
    summary_metrics[col] = summary_metrics[col].round(3)

# Orden de columnas más legible.
summary_metrics = summary_metrics[
    [
        "embedding_base", "variant", "index_type", "n_queries",
        "mean_semantic_score_global_at10", "sd_semantic_score_global_at10",
        "se_semantic_score_global_at10", "ci95_semantic_score_global_at10",
        "mean_semantic_score_at10", "sd_semantic_score_at10",
        "mean_functional_score_at10", "sd_functional_score_at10",
        "mean_memory_score_at10", "sd_memory_score_at10",
    ]
]

display(summary_metrics)

,embedding_base,variant,index_type,n_queries,mean_semantic_score_global_at10,sd_semantic_score_global_at10,se_semantic_score_global_at10,ci95_semantic_score_global_at10,mean_semantic_score_at10,sd_semantic_score_at10,mean_functional_score_at10,sd_functional_score_at10,mean_memory_score_at10,sd_memory_score_at10
0,Dialog2Flow,dinamico,HNSW,100,3.664,0.643,0.064,0.126,3.687,0.637,3.669,0.641,3.659,0.647
1,Dialog2Flow,dinamico,IVF,100,3.672,0.647,0.065,0.127,3.704,0.621,3.683,0.650,3.664,0.652
2,Dialog2Flow,dinamico,IVFPQ,100,3.593,0.707,0.071,0.138,3.605,0.706,3.599,0.713,3.570,0.714
3,Dialog2Flow,estatico,HNSW,100,3.377,0.757,0.076,0.148,3.384,0.755,3.411,0.771,3.395,0.766
4,Dialog2Flow,estatico,IVF,100,3.401,0.759,0.076,0.149,3.395,0.760,3.423,0.761,3.400,0.761
5,Dialog2Flow,estatico,IVFPQ,100,3.315,0.825,0.083,0.162,3.311,0.824,3.366,0.849,3.338,0.831

## 1️⃣5️⃣ Comparación pareada: dinámico vs estático por query

Además del promedio global de `MSS@10`, calculamos si la variante dinámica supera a la estática **query por query**.

Esto permite verificar si una mejora promedio se distribuye de forma consistente o si aparece sólo por algunos casos extremos.

Para cada combinación `embedding_base × index_type` calculamos:

- `mean_delta_dynamic_static`: diferencia media `MSS@10 dinámico - MSS@10 estático`;
- `median_delta_dynamic_static`: diferencia mediana;
- `pct_dynamic_better`: porcentaje de queries donde dinámico supera a estático;
- `pct_static_better`: porcentaje de queries donde estático supera a dinámico;
- `pct_ties`: porcentaje de empates;
- test de Wilcoxon pareado, como diagnóstico exploratorio.

In [ ]:
# ============================================================
# Comparación pareada: dinámico vs estático por query
# ============================================================

# Cada fila de query_metrics representa SS@10(q) para una query y configuración.
paired_base = query_metrics[[
    "embedding_base",
    "variant",
    "index_type",
    "query_order",
    "mss_at10",
]].copy()

paired_scores = paired_base.pivot_table(
    index=["embedding_base", "index_type", "query_order"],
    columns="variant",
    values="mss_at10",
).reset_index()

# Normalizamos nombres de variantes por robustez.
variant_aliases = {
    "estatico": "static",
    "estático": "static",
    "static": "static",
    "independiente": "static",
    "dinamico": "dynamic",
    "dinámico": "dynamic",
    "dynamic": "dynamic",
    "acumulativo": "dynamic",
    "acumulativa": "dynamic",
}

renames = {}
for col in paired_scores.columns:
    key = str(col).strip().lower()
    if key in variant_aliases:
        renames[col] = variant_aliases[key]
paired_scores = paired_scores.rename(columns=renames)

required_cols = {"static", "dynamic"}
missing = required_cols - set(paired_scores.columns)
if missing:
    raise ValueError(
        f"Faltan columnas de variante para comparación pareada: {missing}. "
        f"Columnas disponibles: {paired_scores.columns.tolist()}"
    )

paired_scores["delta_dynamic_static"] = paired_scores["dynamic"] - paired_scores["static"]

EPS = 1e-9
paired_scores["dynamic_better"] = paired_scores["delta_dynamic_static"] > EPS
paired_scores["static_better"] = paired_scores["delta_dynamic_static"] < -EPS
paired_scores["tie"] = paired_scores["delta_dynamic_static"].abs() <= EPS

# Test de Wilcoxon pareado como diagnóstico exploratorio.
try:
    from scipy.stats import wilcoxon
    SCIPY_AVAILABLE = True
except Exception:
    SCIPY_AVAILABLE = False

rows = []
for (embedding_base, index_type), group in paired_scores.groupby(["embedding_base", "index_type"], sort=False):
    deltas = group["delta_dynamic_static"].dropna()

    if SCIPY_AVAILABLE and len(deltas) > 0 and not np.allclose(deltas, 0):
        try:
            stat, p_value = wilcoxon(deltas)
        except Exception:
            stat, p_value = np.nan, np.nan
    else:
        stat, p_value = np.nan, np.nan

    n_queries = group["query_order"].nunique()
    n_dynamic_better = int(group["dynamic_better"].sum())
    n_static_better = int(group["static_better"].sum())
    n_ties = int(group["tie"].sum())

    rows.append({
        "embedding_base": embedding_base,
        "index_type": index_type,
        "n_queries": n_queries,
        "mean_static_mss_at10": group["static"].mean(),
        "mean_dynamic_mss_at10": group["dynamic"].mean(),
        "mean_delta_dynamic_static": deltas.mean(),
        "median_delta_dynamic_static": deltas.median(),
        "sd_delta_dynamic_static": deltas.std(),
        "n_dynamic_better": n_dynamic_better,
        "n_static_better": n_static_better,
        "n_ties": n_ties,
        "pct_dynamic_better": n_dynamic_better / n_queries if n_queries else np.nan,
        "pct_static_better": n_static_better / n_queries if n_queries else np.nan,
        "pct_ties": n_ties / n_queries if n_queries else np.nan,
        "wilcoxon_statistic": stat,
        "wilcoxon_p_value": p_value,
    })

dynamic_static_summary = pd.DataFrame(rows)

# Redondeo sólo para visualización/exportación resumida.
for col in dynamic_static_summary.select_dtypes(include=["float"]).columns:
    dynamic_static_summary[col] = dynamic_static_summary[col].round(4)

# Pivots útiles para inspección rápida.
pivot_delta_dynamic_static = dynamic_static_summary.pivot_table(
    index="embedding_base",
    columns="index_type",
    values="mean_delta_dynamic_static",
)

pivot_pct_dynamic_better = dynamic_static_summary.pivot_table(
    index="embedding_base",
    columns="index_type",
    values="pct_dynamic_better",
)

# Orden de columnas consistente.
index_order = ["IVF", "HNSW", "IVFPQ"]
pivot_delta_dynamic_static = pivot_delta_dynamic_static[[c for c in index_order if c in pivot_delta_dynamic_static.columns]]
pivot_pct_dynamic_better = pivot_pct_dynamic_better[[c for c in index_order if c in pivot_pct_dynamic_better.columns]]

print("Resumen pareado dinámico vs estático")
display(dynamic_static_summary)

print("Δ MSS@10 = dinámico - estático")
display(pivot_delta_dynamic_static)

print("Porcentaje de queries donde dinámico > estático")
display(pivot_pct_dynamic_better)

Resumen pareado dinámico vs estático

,embedding_base,index_type,n_queries,mean_static_mss_at10,mean_dynamic_mss_at10,mean_delta_dynamic_static,median_delta_dynamic_static,sd_delta_dynamic_static,n_dynamic_better,n_static_better,n_ties,pct_dynamic_better,pct_static_better,pct_ties,wilcoxon_statistic,wilcoxon_p_value
0,Dialog2Flow,HNSW,100,3.377,3.664,0.287,0.30,0.7279,67,24,9,0.67,0.24,0.09,1031.5,0.0000
1,Dialog2Flow,IVF,100,3.401,3.672,0.271,0.25,0.7428,63,26,11,0.63,0.26,0.11,1006.0,0.0000
2,Dialog2Flow,IVFPQ,100,3.315,3.593,0.278,0.20,0.8097,57,35,8,0.57,0.35,0.08,1329.0,0.0016

Δ MSS@10 = dinámico - estático

index_type        IVF   HNSW  IVFPQ
embedding_base
Dialog2Flow     0.271  0.287  0.278

Porcentaje de queries donde dinámico > estático

index_type       IVF  HNSW  IVFPQ
embedding_base
Dialog2Flow     0.63  0.67   0.57

## 1️⃣6️⃣ Tabla compacta para el paper

Esta es la tabla que conversa con la hipótesis metodológica:

- filas: embedding base;
- columnas: variante estática/dinámica + técnica ANN;
- valor principal: `Mean Semantic Score@10` (`MSS@10`);
- complemento: desvío estándar entre consultas (`SD`).

No repetimos `Recall@10` porque ya está reportado en la tabla ANN principal del paper. Esta tabla agrega la lectura semántico-funcional de las recuperaciones.

In [ ]:
# Pivot principal: media de MSS@10.
pivot_mss_mean = summary_metrics.pivot_table(
    index="embedding_base",
    columns=["variant", "index_type"],
    values="mean_semantic_score_global_at10",
)

# Pivot complementario: desvío estándar de MSS@10 entre queries.
pivot_mss_sd = summary_metrics.pivot_table(
    index="embedding_base",
    columns=["variant", "index_type"],
    values="sd_semantic_score_global_at10",
)

# Ordenamos columnas de forma estable.
ordered_cols = []
for variant in ["estatico", "dinamico"]:
    for idx in ["IVF", "HNSW", "IVFPQ"]:
        if (variant, idx) in pivot_mss_mean.columns:
            ordered_cols.append((variant, idx))

pivot_mss_mean = pivot_mss_mean[ordered_cols]
pivot_mss_sd = pivot_mss_sd[[c for c in ordered_cols if c in pivot_mss_sd.columns]]

print("MSS@10 — media")
display(pivot_mss_mean)

print("MSS@10 — desvío estándar entre queries")
display(pivot_mss_sd)

# Tabla lista para paper: "media ± SD" en cada celda.
pivot_mss_mean_sd = pivot_mss_mean.copy().astype(object)
for col in pivot_mss_mean.columns:
    for idx in pivot_mss_mean.index:
        mean_val = pivot_mss_mean.loc[idx, col]
        sd_val = pivot_mss_sd.loc[idx, col] if col in pivot_mss_sd.columns else np.nan
        if pd.isna(mean_val):
            pivot_mss_mean_sd.loc[idx, col] = ""
        elif pd.isna(sd_val):
            pivot_mss_mean_sd.loc[idx, col] = f"{mean_val:.3f}"
        else:
            pivot_mss_mean_sd.loc[idx, col] = f"{mean_val:.3f} ± {sd_val:.3f}"

print("MSS@10 — media ± SD")
display(pivot_mss_mean_sd)

MSS@10 — media

variant        estatico               dinamico
index_type          IVF   HNSW  IVFPQ      IVF   HNSW  IVFPQ
embedding_base
Dialog2Flow       3.401  3.377  3.315    3.672  3.664  3.593

MSS@10 — desvío estándar entre queries

variant        estatico               dinamico
index_type          IVF   HNSW  IVFPQ      IVF   HNSW  IVFPQ
embedding_base
Dialog2Flow       0.759  0.757  0.825    0.647  0.643  0.707

MSS@10 — media ± SD

variant              estatico                                     dinamico  \
index_type                IVF           HNSW          IVFPQ            IVF
embedding_base
Dialog2Flow     3.401 ± 0.759  3.377 ± 0.757  3.315 ± 0.825  3.672 ± 0.647

variant
index_type               HNSW          IVFPQ
embedding_base
Dialog2Flow     3.664 ± 0.643  3.593 ± 0.707

## 1️⃣7️⃣ Ejemplos textuales con juicio del LLM

Además de la tabla agregada, conviene inspeccionar ejemplos concretos. Esta sección muestra una consulta, sus vecinos y las razones breves del LLM juez.

Esto es útil para detectar problemas como:

- similitud lexical sin equivalencia funcional;
- vecinos del mismo dominio pero de momento conversacional distinto;
- buenos vecinos dinámicos que no aparecen en la representación estática;
- degradación semántica por cuantización en IVFPQ.

In [ ]:
def mostrar_vecinos_con_scores(
    df_scores: pd.DataFrame,
    embedding_base: str = "Dialog2Flow",
    variante: str = "dinamico",
    index_type: str = "HNSW",
    query_order: int = 0,
    top_n: int = 10,
):
    sub = df_scores[
        (df_scores["embedding_base"] == embedding_base) &
        (df_scores["variant"] == variante) &
        (df_scores["index_type"] == index_type) &
        (df_scores["query_order"] == query_order)
    ].sort_values("neighbor_rank").head(top_n)

    if sub.empty:
        print("No hay registros para ese filtro.")
        return

    first = sub.iloc[0]
    display(Markdown(f"### Consulta `{query_order}` — {embedding_base} / {variante} / {index_type}"))
    display(Markdown("**Situación de consulta:**"))
    print(first["query_context"])

    cols = [
        "neighbor_rank",
        "distance",
        "overall_similarity",
        "semantic_similarity",
        "functional_similarity",
        "memory_usefulness",
        "neighbor_utterance",
        "brief_reason",
    ]
    out = sub[cols].copy()
    out["distance"] = out["distance"].round(4)
    display(out)

# Ejemplo con scores.
mostrar_vecinos_con_scores(
    df_scores,
    embedding_base="Dialog2Flow",
    variante="dinamico",
    index_type="HNSW",
    query_order=0,
    top_n=10,
)

### Consulta `0` — Dialog2Flow / dinamico / HNSW

**Situación de consulta:**

[6] user: i 'd also like to find a 4 star hotel with free wifi , please .
[7] system: there are 3 hotels which are 4 stars , two in the west and one in the centre . is there an area which you prefer ?
[8] user: oh , i completely forgot to mention that i will also need a hotel that has free parking . any of the 7 you said have this option ?

,neighbor_rank,distance,overall_similarity,semantic_similarity,functional_similarity,memory_usefulness,neighbor_utterance,brief_reason
4000,1,0.0312,5,5,5,5,"oh, i completely forgot to mention that i will...",Exact match of the query dialogue turns with i...
4001,2,0.0312,5,5,5,5,"Oh, I completely forgot to mention that I will...",Exact match of the query dialogue turns with i...
4002,3,0.0826,4,4,4,4,"there are 3 hotels which are 4 stars , two in ...",Same user request and system response about 4 ...
4003,4,0.0845,5,5,5,5,"huntingdon marriott hotel , the cambridge belf...",Contains the key user request about 4 star hot...
4004,5,0.1067,5,5,5,5,"huntingdon marriott hotel, the cambridge belfr...",Same as neighbor 4 but includes user request t...
4005,6,0.1067,5,5,5,5,"huntingdon marriott hotel, the cambridge belfr...",Same as neighbor 5 with identical dialogue con...
4006,7,0.1087,4,4,4,4,"there are 3 hotels which are 4 stars, two in t...",Similar user request and system response about...
4007,8,0.1087,4,4,4,4,"There are 3 hotels which are 4 stars, two in t...",Same as neighbor 7 with minor differences in c...
4008,9,0.1692,3,3,3,3,i 'd also like to find a 4 star hotel with fre...,User request about 4 star hotel with free wifi...
4009,10,0.1845,3,3,3,3,it should include free parking . the hotel sho...,User requests hotel with free parking but star...

## 1️⃣8️⃣ Exportación de resultados

Se guardan los archivos necesarios para analizar y reportar el experimento:

- recuperaciones top-10 con texto;
- scores individuales del LLM;
- métricas por query/configuración;
- métricas agregadas por configuración;
- comparación pareada dinámico vs estático por query;
- resumen de porcentaje de queries donde dinámico supera a estático;
- tabla pivot de `MSS@10` media;
- tabla pivot de `MSS@10` desvío estándar;
- tabla pivot `MSS@10` media ± SD para el paper.

También se copia todo a Google Drive si está montado.

In [ ]:
fecha_hora_arg = datetime.now(ZoneInfo("America/Argentina/Buenos_Aires")).strftime("%Y%m%d_%H%M%S_ARG")

retrieval_csv = LOCAL_RESULTS_DIR / f"retrieval_top10_textual_{fecha_hora_arg}.csv"
scores_csv = LOCAL_RESULTS_DIR / f"llm_semantic_scores_pairs_{fecha_hora_arg}.csv"
query_metrics_csv = LOCAL_RESULTS_DIR / f"llm_semantic_query_metrics_{fecha_hora_arg}.csv"
summary_csv = LOCAL_RESULTS_DIR / f"llm_semantic_summary_{fecha_hora_arg}.csv"
paired_scores_csv = LOCAL_RESULTS_DIR / f"dynamic_static_query_deltas_{fecha_hora_arg}.csv"
paired_summary_csv = LOCAL_RESULTS_DIR / f"dynamic_static_summary_{fecha_hora_arg}.csv"
pivot_delta_csv = LOCAL_RESULTS_DIR / f"table_delta_dynamic_static_pivot_{fecha_hora_arg}.csv"
pivot_pct_dynamic_better_csv = LOCAL_RESULTS_DIR / f"table_pct_dynamic_better_pivot_{fecha_hora_arg}.csv"
pivot_mean_csv = LOCAL_RESULTS_DIR / f"table_mss_at10_mean_pivot_{fecha_hora_arg}.csv"
pivot_sd_csv = LOCAL_RESULTS_DIR / f"table_mss_at10_sd_pivot_{fecha_hora_arg}.csv"
pivot_mean_sd_csv = LOCAL_RESULTS_DIR / f"table_mss_at10_mean_sd_pivot_{fecha_hora_arg}.csv"
pivot_mean_sd_latex = LOCAL_RESULTS_DIR / f"table_mss_at10_mean_sd_pivot_{fecha_hora_arg}.tex"

# Exportamos.
df_retrieval.to_csv(retrieval_csv, index=False)
df_scores.to_csv(scores_csv, index=False)
query_metrics.to_csv(query_metrics_csv, index=False)
summary_metrics.to_csv(summary_csv, index=False)
paired_scores.to_csv(paired_scores_csv, index=False)
dynamic_static_summary.to_csv(paired_summary_csv, index=False)
pivot_delta_dynamic_static.to_csv(pivot_delta_csv)
pivot_pct_dynamic_better.to_csv(pivot_pct_dynamic_better_csv)
pivot_mss_mean.to_csv(pivot_mean_csv)
pivot_mss_sd.to_csv(pivot_sd_csv)
pivot_mss_mean_sd.to_csv(pivot_mean_sd_csv)

with open(pivot_mean_sd_latex, "w", encoding="utf-8") as f:
    f.write(pivot_mss_mean_sd.to_latex())

print("Archivos locales guardados:")
files_to_copy = [
    retrieval_csv,
    scores_csv,
    query_metrics_csv,
    summary_csv,
    paired_scores_csv,
    paired_summary_csv,
    pivot_delta_csv,
    pivot_pct_dynamic_better_csv,
    pivot_mean_csv,
    pivot_sd_csv,
    pivot_mean_sd_csv,
    pivot_mean_sd_latex,
    CACHE_PATH,
]
for p in files_to_copy:
    print("-", p)

# Copia a Drive si está disponible.
if IN_COLAB:
    semantic_dir = DRIVE_RESULTS_DIR / "semantic_llm"
    semantic_dir.mkdir(parents=True, exist_ok=True)
    for p in files_to_copy:
        shutil.copy(p, semantic_dir / p.name)
    print("\nCopiados a Drive en:", semantic_dir)

Archivos locales guardados:
- resultados_semantic_llm/retrieval_top10_textual_20260529_195719_ARG.csv
- resultados_semantic_llm/llm_semantic_scores_pairs_20260529_195719_ARG.csv
- resultados_semantic_llm/llm_semantic_query_metrics_20260529_195719_ARG.csv
- resultados_semantic_llm/llm_semantic_summary_20260529_195719_ARG.csv
- resultados_semantic_llm/dynamic_static_query_deltas_20260529_195719_ARG.csv
- resultados_semantic_llm/dynamic_static_summary_20260529_195719_ARG.csv
- resultados_semantic_llm/table_delta_dynamic_static_pivot_20260529_195719_ARG.csv
- resultados_semantic_llm/table_pct_dynamic_better_pivot_20260529_195719_ARG.csv
- resultados_semantic_llm/table_mss_at10_mean_pivot_20260529_195719_ARG.csv
- resultados_semantic_llm/table_mss_at10_sd_pivot_20260529_195719_ARG.csv
- resultados_semantic_llm/table_mss_at10_mean_sd_pivot_20260529_195719_ARG.csv
- resultados_semantic_llm/table_mss_at10_mean_sd_pivot_20260529_195719_ARG.tex
- resultados_semantic_llm/llm_semantic_scores_cache_20260529_185158_ARG.jsonl

Copiados a Drive en: /content/drive/MyDrive/Doctorado/Cursos/ANN/TF/resultados/semantic_llm